package model

import "github.com/shopspring/decimal"

type Product struct {
	Id          int32  `json:"id" binding:"required"`
	Price       string `json:"price" binding:"required"`
	PartName    string `json:"name" binding:"required"`
	CostPrice   string `json:"cost_price"`
	ShelfNumber string `json:"shelf_number"`
	Quantity    string `json:"quantity"`
}

// In pkg/db/gen/ (auto-generated by sqlc)
type SearchProductParams struct {
	ID       int32  `json:"id"`       // user.id
	CONCAT   string `json:"concat"`   // search query (used twice)
	CONCAT_2 string `json:"concat_2"` // search query (used twice)
	Limit    int32  `json:"limit"`
}

type SearchProductRow struct {
	ArticleID   int32           `json:"article_id"`
	Price       decimal.Decimal `json:"price"`
	Quantity    decimal.Decimal `json:"quantity"`
	CostPrice   decimal.Decimal `json:"cost_price"`
	ShelfNumber *string         `json:"shelf_number"`
}
